name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build application 
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
          npm i -g @electron-forge/cli
      - name: Windows self-signed certificate
        if: runner.os == 'Windows'
        run: |
          echo "$CERTIFICATE_WINDOWS_PFX" >> encoded.txt
          certutil.exe -decode encoded.txt electron-example.pfx
        shell: bash
        env:
          CERTIFICATE_WINDOWS_PFX : ${{secrets.CERTIFICATE_WINDOWS_PFX}}
      - name: Build application
        run: |
          npm run make
          ls