name: Build

on:
  branches:
    - misc/gh-action
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build application 
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
          npm i -g @electron-forge/cli
      - name: Build application
        run: |
          npm run make
          ls