name: Create-Release

on: push
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 19 * * *'

jobs:
  create-release:
    name: Create release 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        uses: actions/create-release@v1
        env:
          VERSION: v$(node -e "console.log(require('./package.json').version);")
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release for test
          body: |
            Nothing to see here
          draft: false
          prerelease: false


