name: Daily-Release

# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '0 10 * * *'
on:
  push:
    branches:
      - main

jobs:
  daily-release:
    name: Create release 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          node script/bump_version.js
          git add .
          git commit -m "Bump version"
          git push origin main

      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          export VERSION=v$(node -e "console.log(require('./package.json').version);")
          git tag $VERSION
          git push origin $VERSION


