name: Daily-Release

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 10 * * *'

jobs:
  daily-release:
    name: Create release 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump version
        run: |
          node script/bump_version.js
          git config --local user.email "contact@update.rocks"
          git config --local user.name "bot"
          git add .
          git commit -m "Bump version"
          git push origin master
      - name: Create tag
        run: |
          export VERSION=v$(node -e "console.log(require('./package.json').version);")
          git tag $VERSION
          git push origin $VERSION

